using GekkoSuite.Api.Enums;

namespace GekkoSuite.Api.Dtos;

public class CreateOrderDto
{
    /// <summary>The order id, generated by the service before the write.</summary>
    public Guid OrderId { get; set; }

    /// <summary>The tenant the sale belongs to (from the caller's token).</summary>
    public Guid OrganizationId { get; set; }

    /// <summary>The store the sale was rung up at.</summary>
    public Guid StoreId { get; set; }

    /// <summary>The cashier who rang the sale.</summary>
    public Guid SoldByUserId { get; set; }

    /// <summary>The customer this sale is attached to; null for a walk-in sale.</summary>
    public Guid? CustomerId { get; set; }

    /// <summary>How the sale was paid.</summary>
    public PaymentMethod PaymentMethod { get; set; }

    /// <summary>Sum of line (unit price × quantity), computed server-side.</summary>
    public decimal Subtotal { get; set; }

    /// <summary>Order-level discount; always 0 today — there is no discount feature yet.</summary>
    public decimal DiscountTotal { get; set; }

    /// <summary>Sum of each taxable line's tax, computed server-side from the product's own tax rate.</summary>
    public decimal TaxTotal { get; set; }

    /// <summary>Subtotal - discount + tax.</summary>
    public decimal Total { get; set; }

    /// <summary>The priced, validated lines to write.</summary>
    public List<CreateOrderLineDto> Lines { get; set; } = [];
}

public class CreateOrderLineDto
{
    /// <summary>The store_product sold.</summary>
    public Guid ProductId { get; set; }

    /// <summary>How many units.</summary>
    public int Quantity { get; set; }

    /// <summary>Price per unit, snapshotted from the product at sale time — never taken from the client.</summary>
    public decimal UnitPrice { get; set; }
}
